amazon:
  access:
    key: AKIAI677D66QYDGOZOPA
    secret-key: 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
  region: us-east-1
  end-point:
    url: dynamodb.us-east-1.amazonaws.com
    
server:
  port: 8085